config/routes.rb
Rails.application.routes.draw do
  Spree::Core::Engine.routes.draw do
    get '/contact' => "products#contact"
    get '/about' => "products#about"
  end
  mount Spree::Core::Engine, :at => '/'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/spree/home_controller_decorator.rb
Spree::HomeController.class_eval do
	 def index
      @searcher = build_searcher(params.merge(include_images: true))
      @products = @searcher.retrieve_products.sample(3)
      @taxonomies = Spree::Taxonomy.includes(root: :children)
    end
end

app/controllers/spree/products_controller_decorator.rb
Spree::ProductsController.class_eval do
  def contact
  end

  def about
  end
  def index
      @products = Spree::Product.all
      @taxonomies = Spree::Taxonomy.includes(root: :children)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tagz</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/spree/home/index.html.erb
     <div class="intro-header">
         
         <!--Start Container-->
        <div class="container">

            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                        <center> <h1 class="jjj "> Shoe Tags That Enhances Your Shoe Look </h1></center>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <div class="col-md-12 kickback">
      <div class="container">
          <div class="col-md-12">
            <h3 class="kn1">KICK TAGZ</h3>
            <a href="#" class="know">Know more </a>
          </div>
       <div class="col-md-12">
        <p class="tp">
        Kicktagz attach to your laces and provide your sneakers with a sportier look that will make your sneakers pop! This new and exciting sneaker accessory is 100% metal and able to withstand normal wear and tear a typical sneaker endures. Separate yourself from the pack and get your KickTagz today. Stay tuned for more creative designs and colors!
        
           </p>
        </div>
      </div>
    </div>



   <div class="col-md-12">
      <!--start Container-->
         <div class="container">
              <div class="col-md-12 simi">
            <h4> Similar Recommendations </h4></div>
            <div class="col-md-12 apache">
          <% @products.each do |product| %>
          <div class="col-md-4 t8 t9i icmargin8">
            <div class=" row u1">
                        <center>  
                          <h5><%= product.name %></h5>
                          <h5><%= product.sku %></h5>
                          <%= link_to product_image(product), product_path(product) %>
                        </center>

                        <div class="col-xs-12">
                          <h3>
                            <%= product.price %>$
                          </h3>
                        </div>

                        <div class="col-xs-6">
                          <h5>
                            <%= link_to 'Details' , product_path(product) %>
                          </h5>
                        </div>
                        
                        <div class="col-xs-6">
                          <h5 class="pull-right">
                            <%= form_for :order, :url => populate_orders_url do |f| %>
                              <%= hidden_field_tag "variants[#{product.variants_including_master.first.id
                            }]", 1, :size => 3 %>
                              <%= hidden_field_tag "variant_id", product.variants_including_master.first.id %>
                              <%= hidden_field_tag "quantity", 1 %>
                              <%= link_to 'ADD TO BAG', '#', :onclick => "$(this).parent().submit(); return false;", :class => "button" %>
                            <% end %>
                          </h5>
                        </div>
             </div>
          </div>
        <% end %>
        </div>

      </div>   
            
        
    </div>

app/views/spree/layouts/spree_application.html.erb
<!DOCTYPE html>
<html lang="en">
<!--Header-->
<head>
    <%= render partial: 'spree/shared/head' %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">


    <!-- Bootstrap Core CSS -->
    <%= stylesheet_link_tag  'spree/frontend/bootstrap.min.css', media: 'all', 'data-turbolinks-track' => true %>

    <%= stylesheet_link_tag  'spree/frontend/style.css', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag  'spree/frontend/font-awesome.min.css', media: 'all', 'data-turbolinks-track' => true %>
    <!-- Custom Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,300italic,300" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    
    

</head>
    <!--End Header-->

<body>
    
   <!--star Navbar-->
   <nav class="navbar navbar-default navbar-fixed-top topnav n2n2 n2n22" role="navigation">
        <div class=" topnav">
            <div class="floatmed">
            <a class="navbar-brand topnav visible-xs navtextcol" href="/"><%= image_tag "spree/frontend/logo1.png" , class: 'logostyle' %></a>
            <% if spree_current_user %>
                <%= link_to 'LOG OUT', destroy_spree_user_session_path, class:  "navbar-brand topnav  navtextcol nextcol hheader tt " %>
            <% else %>
                <%= link_to 'LOG IN', spree_login_path, class:  "navbar-brand topnav  navtextcol nextcol hheader tt " %>
                
            <% end %>    
                <a id="link-to-cart"  class="navbar-brand topnav  nextcol1 hheader2 tt2" data-hook>
        <noscript>
          <%= link_to Spree.t(:cart), '/cart' %>
        </noscript>
        &nbsp;
      </a>
      <script>Spree.fetch_cart()</script></a>
            
            </div>
   
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header navh">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand topnav hidden-xs " href="/"><%= image_tag "spree/frontend/logo1.png" , class: 'logostyle' %></a>
            </div>
            
               <div class="col-md-12 header2 nn1111">
                   <div class="col-md-6 col-md-offset-6">
                   
         <ul class="nav navbar-nav navbar-right hidden-xs nextcol3">
             
    <li>
                        <a class=" fweight1 "  style="color:#1288c5"href="/">Home</a>
                    </li>
                      <li>
                        <a class=" fweight1" style="color:#1288c5" href="/products">Tagz</a>
                    </li>
                    <li>
                        <a class=" fweight1" style="color:#1288c5" href="/about">About Tagz</a>
                    </li>
                    <li>
                        <a class=" fweight1" style="color:#1288c5" href="/contact">Contact</a>
                    </li>
    
        </ul>
                   </div>
    </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right visible-xs">
                    <li>
                        <a class=" fweight1" style="color:#1288c5" href="/">Home</a>
                    </li>
                     <li>
                        <a class=" fweight1" style="color:#1288c5" href="/products">Tagz</a>
                    </li>
                    <li>
                        <a class=" fweight1"  style="color:#1288c5"href="/about">About Tagz</a>
                    </li>
                    <li>
                        <a class=" fweight1 " style="color:#1288c5" href="/contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav> <!--End Navbar-->
 
          <%= yield %>
    
     <!-- End of Page Content -->

    <!-- /.intro-header -->

   <!--Start Footer-->
 
<footer class="footer">
        
        <div class="col-md-12 fcolor">    
                
                      <ul class="list-inline footer45">
                        <li>
                            <a href="#">Terms and Conditions</a>
                        </li>
                        <li class="footer-menu-divider">|</li>
                        <li>
                            <a href="#about">FAQ</a>
                        </li>
                        <li class="footer-menu-divider">|</li>
                        <li>
                            <a href="#services">Contact</a>
                        </li>
                        
                    </ul>
                   
                
        </div>
     
    </footer>     

</body>

</html>

app/views/spree/orders/_form.html.erb
<%= render partial: 'spree/shared/error_messages', locals: { target: @order } %>
<div class="col-md-12 rcart3">
   <div id="page-wrap">

  <h1 class="rcart2 rcart002 icmargin5" >Cart</h1>
   
  <table>
    <thead>
    <tr>
      <th class="rcart1"></th>
      <th class="rcart1"></th>
            <th class="rcart1"><center><h4 class="rcart4">QUANTITY</h4></center></th>
            <th class="rcart1"> <center><h4 class="rcart4">DELIVERY</h4></center></th>
            <th class="rcart1"><center> <h4 class="rcart4" >SUBTOTAL</h4></center></th>
    </tr>
    </thead>
    <tbody>
    <%= render partial: 'spree/orders/line_item', collection: order_form.object.line_items, locals: { order_form: order_form } %>
    </tbody>
    
  </table>
      
  <%= button_tag class: 'btn btn-default btn-lg btnonh submit dupsub subbtn tmargin rcart004 rcart9 rcart001 icmargin4 ', id: 'checkout-link', name: 'checkout', :style => "color:#FFFFFF" do %>
                <span class="network-name">PROCEED</span>
              <% end %>
</div>
          
</div>

app/views/spree/orders/_line_item.html.erb
<% variant = line_item.variant %>

<%= order_form.fields_for :line_items, line_item do |item_form| %>
  <tr class="line-item">
    <td class="rcart1" data-hook="cart_item_image">
      <% if variant.images.length == 0 %>
        <%= link_to small_image(variant.product, class: 'rcart6 rcart7'), variant.product %>
      <% else %>
        <%= link_to image_tag(variant.images.first.attachment.url(:product), class: 'rcart6 rcart7'), variant.product %>
      <% end %>
    </td>
    <td class="rcart1"><h4 class="rcart4 rcart10"><%= line_item.name %></h4> <h4 class="rcart4 rcart10"><%= line_item.sku %></h4></td>
    <td class="rcart1">
                
                <!-- <center><h4 class="rcart4"><%- line_item.quantity %><%= item_form.number_field :quantity, min: 0, class: "form-control line_item_quantity", size: 5 %></h4></td></center> -->

                <center><h4 class="rcart4"><%= line_item.quantity %><%= item_form.hidden_field :quantity, min: 0, class: "form-control line_item_quantity", size: 5 %></h4></td></center>

       <td class="rcart1"><center><h4 class="rcart4">FREE</h4></td></center>
    <td class="rcart1" data-hook="cart_item_total"><center><h4 class="rcart4 rcart20">
      <%= line_item.display_amount.to_html unless line_item.quantity.nil? %></h4></center>
    
      <%= link_to content_tag(:span, 'REMOVE', class: 'btn btn-info hbtn1 ccbtn rcart5 rcart8 icmargin3'), '#', class: 'delete', id: "delete_#{dom_id(line_item)}" %>
    </td>
  </tr>
<% end %>

app/views/spree/orders/edit.html.erb
  <% if @order.line_items.empty? %>
    
<a name="about"></a>
  
        <div class="container">

            <div class="row rfloat">
                <div class="col-lg-12 cart021">
                    <div class="intro-message">
                        
        
        
        <div class="col-md-12 talign">
            <h3 class="abt icmargin2"> Cart</h3>
     
            <h4 class="hcol"> Common you need to have something in bag !</h4></div>
        <div class="col-md-12 cart022">
         <%= link_to "SHOP", products_path, class: "btn btn-default btn-lg btnonh submit dupsub subbtn tmargin vvt vvt1", :style => "color:#FFFFFF" %>
        </div>
                    </div>
                </div>
            </div>

        </div>

  <% else %>
    <div data-hook="outside_cart_form">
      <%= form_for @order, url: update_cart_path, html: { id: 'update-cart' } do |order_form| %>
        <div data-hook="inside_cart_form">

          <div data-hook="cart_items" class="table-responsive">
            <%= render partial: 'form', locals: { order_form: order_form } %>
          </div>

          <!-- <div class="links col-md-6 navbar-form pull-right text-right" data-hook="cart_buttons">
            <div class="form-group">
              <%= button_tag class: 'btn btn-primary', id: 'update-button' do %>
                <%= Spree.t(:update) %>
              <% end %>
              <%= button_tag class: 'btn btn-lg btn-success', id: 'checkout-link', name: 'checkout' do %>
                <%= Spree.t(:checkout) %>
              <% end %>
            </div>
          </div> -->
        </div>
      <% end %>
    </div>

    <!-- <div id="empty-cart" class="col-md-6 pull-left" data-hook>
      <%= form_tag empty_cart_path, method: :put do %>
        <p id="clear_cart_link" data-hook>
          <%= submit_tag Spree.t(:empty_cart), class: 'btn btn-default' %>
          <%= Spree.t(:or) %>
          <%= link_to Spree.t(:continue_shopping), products_path, class: 'continue' %>
        </p>
      <% end %>
    </div> -->
  <% end %>
</div>

app/views/spree/products/_cart_form.html.erb
<%= form_for :order, :url => populate_orders_path do |f| %>
  <div class="row" id="inside-product-cart-form" data-hook="inside_product_cart_form" itemprop="offers" itemscope itemtype="https://schema.org/Offer">
    <% if @product.variants_and_option_values(current_currency).any? %>
      <div id="product-variants" class="col-md-6">
        <h3 class="product-section-title"><%= Spree.t(:variants) %></h3>
        <ul class="list-group">
          <% @product.variants_and_option_values(current_currency).each_with_index do |variant, index| %>
            <li>
              <%= radio_button_tag "variant_id", variant.id, index == 0, 'data-price' => variant.price_in(current_currency).money  %>
              <%= label_tag "variant_id_#{ variant.id }" do %>
                <span class="variant-description">
                  <%= variant_options variant %>
                </span>
                <% if variant_price variant %>
                  <span class="price diff"><%= variant_price variant %></span>
                <% end %>
                <% unless variant.can_supply? %>
                  <span class="out-of-stock"><%= Spree.t(:out_of_stock) %></span>
                <% end %>
              <% end %>
            </li>
          <% end%>
        </ul>
      </div>
    <% else %>
      <%= hidden_field_tag "variant_id", @product.master.id %>
    <% end %>

    <% if @product.price_in(current_currency) and !@product.price.nil? %>
      <div data-hook="product_price" class="col-md-5">
        <div id="product-price">
          
          <% if @product.master.can_supply? %>
            <link itemprop="availability" href="https://schema.org/InStock" />
          <% elsif @product.variants.empty? %>
            <br />
            <span class="out-of-stock"><%= Spree.t(:out_of_stock) %></span>
          <% end %>
        </div>

        <div class="add-to-cart">
          <br/>
          <div class="input-group">
            <%= number_field_tag :quantity, 1, :class => 'title form-control', :min => 1 %>
            <span class="input-group-btn">
              <%= button_tag :class => 'btn btn-success', :id => 'add-to-cart-button', :type => :submit do %>
                <%= Spree.t(:add_to_cart) %>
              <% end %>
            </span>
          </div>
        </div>
      </div>
    <% else %>
      <div id="product-price">
        <br>
        <div><span class="price selling" itemprop="price"><%= Spree.t('product_not_available_in_this_currency') %></span></div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/spree/products/about.html.erb
<div class="col-md-12 bodycol">
            <h3 class="abt abtmargtop">About Tagz</h3></div>
       <div class="col-md-12 bgcol bodycol">
        <p class="p1">
          KickTagz is chicago based company that was founded in early 2015. The company is specializes in shoe
            fashion. More specifically, KickTagz manufactures unique shoe accessories that fasten to the lace of the
            customers shoe.The company starts with rough sketches and works with premier graphic designers to
            further refine the design and manufacture final product.KickTagz works with stretegic suppliers that 
            allow the flexibility and competitive cost structure,wich allow kick Tagz to offer an affordable price to 
            customers and keep up with demand of its partners.
        
           </p>
        
     </div>
    
    <!--End of container1-->


<!--Footer-->
  

app/views/spree/products/contact.html.erb
<a name="about"></a>
    
        <!--Start Container-->
        <div class="container">

            <div class="row rfloat">
                <div class="col-lg-12">
                    <div class="intro-message">
                        
        
        
        <div class="col-md-12 talign">
            <h3 class="abt hg1 icmargin"> KickTagz Contact </h3>
        <h5 class="hcol"> Email:info@kicktagz.com</h5>
            <h5 class="hcol"> Phone:847344-3826</h5>
                         <h5 class="hcol"> Address:53 W.Jackson Blvd.#1140</h5></div>
        <div class="col-md-12 talign">
                        <h3 class="abt"> Contact Tagz</h3>
          <input  class="x1 icmargin1 tmargin " type="textbox" placeholder="Name(required)"><br>
          <input  class="x1 tmargin icmargin1" type="varchar" placeholder="Phone Number(required)"><br>
          <input  class="x1 tmargin icmargin1" type="email" placeholder="Email ID(required)"><br>
         <textarea rows="4" cols="50" placeholder="Your Message"  class="x1 icmargin1 tmargin"></textarea><br>
         <a class="btn btn-default btn-lg btnonh submit dupsub subbtn tmargin vvt hg3"> <span class="network-name">SUBMIT </span></a>
          
        </div>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container -->

    
    <!-- /.intro-header -->

    <!-- Page Content -->

   

app/views/spree/products/index.html.erb
    <% @products.each_slice(4).with_index do |slice, index| -%>
      <% if index == (@products.size-1)/4 %>
        <div class="col-md-12" style="top:130px;">
          <div class="container r1 r2">
          <% slice.each do |product| -%>
                <div class="col-md-3 t8 t9i icmargin8">
                  <div class=" row u1">
                            <center>  <h5><%= product.name %></h5>
                            <h5><%= product.sku %></h5>
                            <%= link_to product_image(product), product_path(product) %></center>
                            <div class="col-xs-12">
                            <h3>
                            <%= product.price %>$
                            </h3>
                          </div>
                          <div class="col-xs-6">
                            <h5><%= link_to 'Details' , product_path(product) %></h5>
                          </div>
                          <div class="col-xs-6">
                            <h5 class="pull-right">
                            <%= form_for :order, :url => populate_orders_url do |f| %>
                              <%= hidden_field_tag "variants[#{product.variants_including_master.first.id
                            }]", 1, :size => 3 %>
                              <%= hidden_field_tag "variant_id", product.variants_including_master.first.id %>
                              <%= hidden_field_tag "quantity", 1 %>
                              <%= link_to 'ADD TO BAG', '#', :onclick => "$(this).parent().submit(); return false;", :class => "button" %>
                            <% end %>
                                    
                            </h5>
                          </div>
                  </div>          
                 </div>
          <% end %>
        </div>
        </div>
      <% else %>
        <div class="col-md-12" style="top:130px;">
          <div class="container r1">
          <% slice.each do |product| -%>
                <div class="col-md-3 t8 t9i icmargin8">
                  <div class=" row u1">
                            <center>  <h5><%= product.name %></h5>
                            <h5><%= product.sku %></h5>
                            <%= link_to product_image(product), product_path(product) %></center>
                            <div class="col-xs-12">
                            <h3>
                            <%= product.price %>$
                            </h3>
                          </div>
                          <div class="col-xs-6">
                            <h5><%= link_to 'Details' , product_path(product) %></h5>
                          </div>
                          <div class="col-xs-6">
                            <h5 class="pull-right">
                            <%= form_for :order, :url => populate_orders_url do |f| %>
                              <%= hidden_field_tag "variants[#{product.variants_including_master.first.id
                            }]", 1, :size => 3 %>
                              <%= hidden_field_tag "variant_id", product.variants_including_master.first.id %>
                              <%= hidden_field_tag "quantity", 1 %>
                              <%= link_to 'ADD TO BAG', '#', :onclick => "$(this).parent().submit(); return false;", :class => "button" %>
                            <% end %>
                                    
                            </h5>
                          </div>
                  </div>          
                 </div>
          <% end %>
        </div>
        </div>
      <% end %>
    <% end %>
             

app/views/spree/products/show.html.erb
<a name="about"></a>
    
        <div class="col-md-12 tmagt tag1">
            <!--Start Container-->
        <div class="container t1 t92 icmargin220 icmargin12 icmargin13">
            <div class="col-md-2">
            <%= link_to product_image(@product), product_path(@product) %>
                <!-- /.container --></div>
            <div class="col-md-10 tmarg11">
            
             <h4  class="t4 tmarg1"><%= @product.name %></h4>
            <p class="t5 t51">
                <%= @product.description %>
                </p>
            <h1 class="t5 tagzcst icmargin15"><%= @product.price %>$</h1>
               
            </div>
            <%= render :partial => 'cart_form' %>
    </div>
           <!--End Container-->
        </div>
        
    
   
     <div class="col-md-12">
      <!--Start container-->
         <div class="container">
              <h4 class="similarh nn11 icmargin10"> Similar Recommendations </h4>
             <% @product.taxons.first.products.each do |product| %>
          <div class="col-md-4 t8 t9i icmargin8">
            <div class=" row u1">
                        <center>  <h5><%= product.name %></h5>
                        <h5><%= product.sku %></h5>
                        <%= link_to product_image(product), product_path(product) %></center>
                        <div class="col-xs-12">
                        <h3>
                        <%= product.price %>$
                        </h3>
                        </div>
                        <div class="col-xs-6">
                        <h5><%= link_to 'Details' , product_path(product) %></h5>
                        </div>
                        <div class="col-xs-6">
                        <h5 class="pull-right">
                        <%= form_for :order, :url => populate_orders_url do |f| %>
                          <%= hidden_field_tag "variants[#{product.variants_including_master.first.id
                        }]", 1, :size => 3 %>
                          <%= hidden_field_tag "variant_id", product.variants_including_master.first.id %>
                          <%= hidden_field_tag "quantity", 1 %>
                          <%= link_to 'ADD TO BAG', '#', :onclick => "$(this).parent().submit(); return false;", :class => "button" %>
                        <% end %>
                        </h5>
                        </div>
             </div>
            </div>
        <% end %>  
         </div>   
            
        <!--End container-->
    </div>

app/views/spree/user_registrations/new.html.erb
<a name="about"></a>
    <div class=" introheight">
        <!--Start container-->
        <div class="container">

            <div class="row rfloat">
                <div class="col-lg-12">
                    <div class="intro-message">
                      <div class="col-md-12 talign1">

                        <% @body_id = 'signup' %>
                        <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @user } %>
                        <h3 class="abt icmargin11"> Sign Up</h3>        
                          <%= form_for resource, :as => :spree_user, :url => spree.registration_path do |f| %>
                            <div data-hook="signup_inside_form">
                                  <input  class="x1 smarg icmargin1 " type="textbox" placeholder="User Name"><br>
                                  <%= f.email_field :email, :class => "x1 tmargin icmargin1", :placeholder => Spree.t(:email) %></br>
                                  <%= f.password_field :password, :class => "x1 tmargin icmargin1", :placeholder => Spree.t(:password) %></br>


                          <!--
                                  <%= f.password_field :password_confirmation, :class => "x1 tmargin icmargin1", :placeholder => Spree.t(:confirm_password) %></br> -->


                              <div data-hook="signup_below_password_fields"></div>              
                              <%= f.submit "Sign Up", :class => "btn smarg btn-default btn-lg btnonh submit dupsub subbtn vvt tmargin dupsub", :style => "color:#FFFFFF" %>
                            </div>
                          <% end %>
                          <!-- <div class="text-center">
                            <%= Spree.t(:or) %> 
                              <%= link_to Spree.t(:login_as_existing), spree.login_path %>
                          </div> -->
                          <div data-hook="login_extras"></div>

                      </div>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>

app/views/spree/user_sessions/new.html.erb
<a name="about"></a>
    <div class="introheight">
        <!--Start Container-->
        <div class="container">

            <div class="row rfloat">
                <div class="col-lg-12">
                    <div class="intro-message">
          
                       <div class="col-md-12 talign1">

                          <% @body_id = 'login' %>
                          <h3 class="abt  icmargin11"> Login </h3>
                          <% if flash[:alert] %>
                            <div class="alert alert-danger"><%= flash[:alert] %></div>
                          <% end %>
                          <%= form_for Spree::User.new, :as => :spree_user, :url => spree.create_new_session_path do |f| %>
                            <div id="password-credentials">
                                <%= f.email_field :email, :class => "x1 tmargin icmargin1", :tabindex => 1, autofocus: true, :placeholder => "Email ID" %><br>
                                <%= f.password_field :password, :class => "x1 tmargin icmargin1", :tabindex => 2, :placeholder => "Password" %></br>
                            </div>
                            <!-- <p>
                              <%= f.check_box :remember_me, :tabindex => 3 %>
                              <%= f.label :remember_me, Spree.t(:remember_me) %>
                            </p>
 -->
                            <%= f.submit "LOGIN", :class => "btn btn-default btn-lg btnonh submit dupsub subbtn tmargin vvt", :tabindex => 4, :style => "color:#FFFFFF" %>
                          <% end %>          
                          <!-- <div class="text-center">
                            <%= Spree.t(:or) %> 
                                <%= link_to Spree.t(:create_a_new_account), spree.signup_path %> |
                                <%= link_to Spree.t(:forgot_password), spree.recover_password_path %>
                          </div> -->
                          <div data-hook="login_extras"></div>
                          
          
                        </div>
                    </div>
                    <%= link_to 'Sign up!', spree_signup_path %>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>